# Default profile for local development
spring.profiles.active=local

# JWT
jwt.secret=CollegeRideSharingSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong2024
jwt.expiration=86400000

# Brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=2507harshit@gmail.com
brevo.sender.name=LNCTShares

# Frontend
frontend.url=http://localhost:5173

# Web Push / VAPID
vapid.public.key=BAUECb02vsId55f2hfW_6Y0_DEWVcCew4dFMlJGRSJR5lMa5YznJ6t7PZQo0qsiuENHfifkgHRrKKtDEMQJfDIE
vapid.private.key=u64xQV7C--o7gKuL9Hjw9z01WFZqvDQOT69-EJxyyZ8
vapid.subject=mailto:2507harshit@gmail.com